services:
  app:
    build: .
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - laravelnet
    depends_on:
      - pgsql

  pgsql:
    image: postgres:17
    restart: unless-stopped
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    networks:
      - laravelnet
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE:-progress_tracker}",
          "-U",
          "${DB_USERNAME:-progress_user}",
        ]
      retries: 3
      timeout: 5s

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - nginx_logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
    networks:
      - laravelnet
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.progress-tracker.rule=Host(`progress.stanrunge.dev`)"
      - "traefik.http.routers.progress-tracker.entrypoints=web,websecure"
      - "traefik.http.routers.progress-tracker.tls.certresolver=myresolver"
      - "traefik.http.services.progress-tracker.loadbalancer.server.port=80"
      - "traefik.http.middlewares.laravel-headers.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.laravel-headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.laravel-headers.headers.customResponseHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.laravel-security.headers.stsSeconds=31536000"
      - "traefik.http.routers.progress-tracker.middlewares=laravel-headers,laravel-security"

networks:
  laravelnet:
    driver: bridge
  traefik_net:
    external: true

volumes:
  dbdata:
  nginx_logs:
